general:
  minCellVoltage: 3
  gearRatio: 3.6
odrives:
  newConfig: false
  brake_resistance: 0
  current_lim: 15
  calibration_current: 10
  vel_limit: 500000
  axis_inverted_forward_direction:
  - true
  - false
  - true
  - false
  serialnumber0: 206739834D4D
  serialnumber1: 204F39824D4D
  pos_gain: 20.0
  vel_gain: 0.0005
  vel_integrator_gain: 0.005
